
export const roomsList = {
    All: [
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
      { roomNo: '01', bedType: 'Single Bed',status:"Available",floor:"1" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
    ],
    Available: [
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
      { roomNo: '03', bedType: 'Single Bed',status:"Available",floor:"3" },
    ],
    Occupied: [
      { roomNo: '03', bedType: 'Double Bed',status:"Occupied" ,floor:"3"},
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      { roomNo: '02', bedType: 'Double Bed', status:"Occupied",floor:"2" },
      
    ],
    Overdue:[
        { roomNo: '04', bedType: 'Double Bed',status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
        { roomNo: '03', bedType: 'Double Bed', status:"Overdue",floor:"3" },
    ]
  };

export default { roomsList }